### ISSUE TITLE
运行报错：def run_(self, *args, **kwargs) -> dict[str: int]: # 这里run是可以在外部更新的函数 TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by lxj0276** [wjsbjl/use-gplearn-to-generate-CTA-factor#5]
toolkit/backtest.py的347行
报错信息：
def run_(self, *args, **kwargs) -> dict[str: int]: # 这里run是可以在外部更新的函数
TypeError: 'type' object is not subscriptable

**Comment by wjsbjl** [comment]
建议开debug模式看卡在哪了，应该是数据格式有问题

**Comment by wjsbjl** [comment]
建议开debug模式看卡在哪了，应该是数据格式有问题
